### What's in the Notebook?
I practiced a few common feature engineering techniques which I am sharing here in this notebook.

In [1]:
# imports
import pandas as pd
import numpy as np
import sklearn

In [2]:
# One-Hot Encoding
data= {'color': ['Red', 'Green', 'Velvet', 'Brown', 'Green', 'Red', 'Brown', 'Brown']}

In [3]:
df= pd.DataFrame(data)

df

    color
0     Red
1   Green
2  Velvet
3   Brown
4   Green
5     Red
6   Brown
7   Brown

In [5]:
# the actual one hot encoding step
df_encoded= pd.get_dummies(df, columns= ['color'])
df_encoded

   color_Brown  color_Green  color_Red  color_Velvet
0        False        False       True         False
1        False         True      False         False
2        False        False      False          True
3         True        False      False         False
4        False         True      False         False
5        False        False       True         False
6         True        False      False         False
7         True        False      False         False

In [6]:
# Binning
data = {'Age': [23, 45, 18, 34, 67, 50, 21]}
df = pd.DataFrame(data)

In [7]:
df

   Age
0   23
1   45
2   18
3   34
4   67
5   50
6   21

In [10]:
# let's make bins
bins= [0, 20, 40, 60, 100]
labels= ['0-20', '21-40', '41-60', '61-100']
df['Age-Group']= pd.cut(df['Age'], bins= bins, labels=labels)
df

   Age Age-Group
0   23     21-40
1   45     41-60
2   18      0-20
3   34     21-40
4   67    61-100
5   50     41-60
6   21     21-40

In [11]:
# Feature Splitting
data = {'Full_Address': [
    '123 Elm St, Springfield, 12345', '456 Oak Rd, Shelbyville, 67890']}
df = pd.DataFrame(data)

In [12]:
df

                     Full_Address
0  123 Elm St, Springfield, 12345
1  456 Oak Rd, Shelbyville, 67890

In [13]:
# Using regular expressions
df[['Street', 'City', 'Zipcode']] = df['Full_Address'].str.extract(
    r'([0-9]+\s[\w\s]+),\s([\w\s]+),\s(\d+)')

In [14]:
df

                     Full_Address      Street         City Zipcode
0  123 Elm St, Springfield, 12345  123 Elm St  Springfield   12345
1  456 Oak Rd, Shelbyville, 67890  456 Oak Rd  Shelbyville   67890